root = "."      # The root directory of the project
tmp_dir = "tmp" # Temporary directory for Air

[build]
bin = "tmp/main"                   # Binary location
cmd = "go build -o tmp/main ./cmd/server"
exclude = ["tmp/*", "client/*"]
include = ["**/*.go"]
ignore = ["tmp/*"]
